### PR TITLE
Ignore commented out test functions

### PR DESCRIPTION
**Pull request by yshym**
Fixes https://github.com/exercism/emacs-lisp-test-runner/issues/47

["your-birthday" test](https://github.com/exercism/emacs-lisp/blob/f456be6ee9c2ff766ef296602cc5aec3486daeea/exercises/practice/gigasecond/gigasecond-test.el#L38-L41) which is commented out wasn't ignored by interpreter

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Great work! Could you perhaps add a test case that verifies the behavior? It should be added here: https://github.com/exercism/emacs-lisp-test-runner

Thanks!

**Comment by yshym** [comment]
I'll merge the PR after adding relevant test case

**Comment by yshym** [comment]
@ErikSchierboom Let me know, if the test case is ok and if it is we can merge the PR

**Comment by ErikSchierboom** [comment]
@yshym Yep that's perfect! Please merge

**Comment by yshym** [comment]
> @yshym Yep that's perfect! Please merge

No permission

**Comment by ErikSchierboom** [comment]
Done. Thanks!

**Pull request merged**
